"""Initial migration

Revision ID: 0d6225d9fbb5
Revises: d5cf9aeccc57
Create Date: 2025-05-09 15:52:32.909432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6225d9fbb5'
down_revision: Union[str, None] = 'd5cf9aeccc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
